export enum EnvKeys {
  HTTP_PORT = 'HTTP_PORT',

  JWT_SECRET = 'JWT_SECRET',
  JWT_SECRET_RE = 'JWT_SECRET_RE',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_DATABASE = 'DB_DATABASE',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_SECRET_ID = 'GITHUB_SECRET_ID',
  GITHUB_LOGIN_URL = 'GITHUB_LOGIN_URL',

  XQUARE_LOGIN_URL = 'XQUARE_LOGIN_URL',

  X_API_Key = 'X_API_Key',
  DEAMA_COIN_BC_SERVER_URL = 'DEAMA_COIN_BC_SERVER_URL',

  GEMINI_KEY = 'GEMINI_KEY',
}
